version: '3'
services:
  image-shifter:
    container_name: image-shifter
    build: .
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2000M
        reservations:
          cpus: '1'
          memory: 1000M